### ISSUE TITLE
推广问题

### ISSUE THREAD

**Issue by xunwumizhi** [wangwei2009/spatial-temporal-LCMV#1]
1.代码里面计算Rvv和Ryy是手动定位静音段和语音段，累加然后全局取平均？
2.Rvv不需要更新吗
3.如果按帧处理，帧长和滤波器长度怎么关联

恳请解答

**Comment by wangwei2009** [comment]
1. 实际中Rvv需要利用VAD在无语音段更新，Ryy如果声源不动的就只用计算一次，如果声学环境变化的话，可以对Rvv跟Ryy做全局递推更新
2. 如上，Rvv实际中需要结合VAD进行更新，只不过我的代码里噪声基本平稳，所以我只估计了一次
3. 我这里是按点处理的，我的理解是，这里的方法都是在时域处理，因此滤波器长度应该是等于帧长

时间有些久了，可能我的理解也有误，如果你有什么不同的看法欢迎提出交流
